### ISSUE TITLE
Streamline directory structure of Hamr apps

### ISSUE THREAD

**Issue by nikochiko** [pipalacademy/boring-serverless#10]
Currently all app data is dumped into the app directory that has source code, database, any other files created during runtime (like `rajdhani.mail` for rajdhani). This can be re-organized.

This would change how the web server needs to serve apps. Those changes are out of scope of this issue, and should be dealt with in a separate issue using the conventions defined here. non-WSGI dynamic apps are also out of scope of this issue.

As part of this issue, changes should be made to how the first deployment of an app is done, and where `git pull` is executed on subsequent updates.

There are two modes an app can be served in: static or dynamic. Static is for completely static sites with no CGI or any other scripts involved. When a web server's FileServer should be good enough.
The other mode is dynamic sites, where some server-side scripts are needed. Static assets can still be served directly by the web-server in this case.

Runner is the CGI app runner that would be responsible for redirecting output of logs to proper logfile or setting the correct environment variables, for example.

```
/apps/app-name        $APP_ROOT
|__ app/
|__ bin/
|__ logs/
|__ public/
|__ private/
|__ site/
|__ tmp/               $TMPDIR
|__ misc_by_users_choice/
```

- `app/`: For source code as deployed by the user. This should have the pre/post-pull scripts if any.
- `bin/`: For any third party binary installations, that may be used by the app or in one of the scripts.
- `logs/`: Directory for storing all logs. Recommended way is to keep a single `app.log` file for everything, but a single app may choose to have multiple loggers that write to different files.
- `public/`: For assets of dynamic apps. Served by web server as `/public/*`
- `private/`: For private assets, to be consumed by the app during runtime. 
- `site/`: For static sites. When this dir exists, the server should only serve from this directory and no CGI scripts
- `tmp/`: The temporary directory for any files created during runtime. The runner should set the `$TMPDIR` before running.
- There could be other miscellaneous directories as decided by the user

Some questions:
- [X] Is `/var/` really necessary, or should we recommend the user put files into `$APP_BASE_DIR` directly? - updated to have flat directories in top-level APP_ROOT
- [X] Would it be better to put logs into `/var/log` instead of `/logs/`, following unix conventions? - `/logs/`
- [X] Would it be good to have a directory for configurations too? Like `/etc/` or `/config/`. Maybe a single `config.yml` for the whole app that defines app-specific env vars? - up to the users.

**Comment by anandology** [comment]
Can we call it `$APP_ROOT` instead of `$APP_BASE_DIR`? 

Flat is better than nested. Let's keep everything in the top-level. 

> Would it be good to have a directory for configurations too? Like /etc/ or /config/. Maybe a single config.yml for the whole app that defines app-specific env vars?

Let the users figure out how they want to use it. We don't have to enforce a `var` or `etc`.

**Comment by nikochiko** [comment]
One choice we have in web server's priority order is whether we allow a mix of static site + dynamic site depending on the route.
Not depending on the `public/` directory, but for example when only the landing page is static, or only `/blog/*` is static.

This could be implemented by using CGI script as a fallback only.

**Comment by anandology** [comment]
Can we do the simple case first and think about this feature after that is done?

**Comment by nikochiko** [comment]
Yes, sounds good.

**Comment by nikochiko** [comment]
> site/: For static sites. When this dir exists, the server should only serve from this directory and no CGI scripts

It's getting a little tricky to have an Apache configuration that does this.
I am trying a [VirtualDocumentRoot](https://httpd.apache.org/docs/2.4/mod/mod_vhost_alias.html#virtualdocumentroot) directive, but that cannot be used in an `<If></If>` context.
